#L pm templates
echo "b 0p5"

./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_b_0p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_b_0p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_b_0p5.root pt7 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_b_cfromg_0p5.root pt7 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_b_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_b_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_b_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_b_cfromg_0p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_0p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_0p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_0p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_0p5.root pt4 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_0p5.root pt4 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_0p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_0p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_0p5.root pt6 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_0p5.root pt6 DoubleBH DoubleT results doubleBLpt1

echo "c 0p5"

./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_c_0p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_c_0p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_c_0p5.root pt7 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_c_l_0p5.root pt7 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_c_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_c_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_c_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_c_l_0p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_0p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_0p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_0p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_0p5.root pt4 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_0p5.root pt4 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_0p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_0p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_0p5.root pt6 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_0p5.root pt6 DoubleBH DoubleT results doubleBLpt1

echo "l 0p5"

./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_l_0p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_l_0p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_l_0p5.root pt7 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_l_0p5.root pt7 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_l_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_l_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_l_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_l_0p5.root pt5 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_0p5.root pt5 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_0p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_0p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_0p5.root pt4 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_0p5.root pt4 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_0p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_0p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_0p5.root pt6 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_0p5.root pt6 DoubleBH Double results doubleBLpt1

echo "cfromg 0p5"

./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_cfromg_0p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_cfromg_0p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_cfromg_0p5.root pt7 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_cfromg_0p5.root pt7 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_cfromg_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_cfromg_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_cfromg_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_cfromg_0p5.root pt5 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_0p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_0p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_0p5.root pt5 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_0p5.root pt5 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_0p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_0p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_0p5.root pt4 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_0p5.root pt4 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_0p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_0p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_0p5.root pt6 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_0p5.root pt6 DoubleBH Double results doubleBLpt1

#L pm templates
echo "b 1p5"

./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_b_1p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_b_1p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_b_1p5.root pt7 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_b_cfromg_1p5.root pt7 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_b_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_b_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_b_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_b_cfromg_1p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_1p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_1p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_1p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_1p5.root pt4 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_1p5.root pt4 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_b_1p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_b_1p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_b_1p5.root pt6 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_b_cfromg_1p5.root pt6 DoubleBH DoubleT results doubleBLpt1

echo "c 1p5"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_c_1p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_c_1p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_c_1p5.root pt7 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_c_l_1p5.root pt7 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_c_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_c_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_c_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_c_l_1p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_1p5.root pt5 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_1p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_1p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_1p5.root pt4 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_1p5.root pt4 DoubleBH DoubleT results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_c_1p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_c_1p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_c_1p5.root pt6 DoubleBM2 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_c_l_1p5.root pt6 DoubleBH DoubleT results doubleBLpt1

echo "l 1p5"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_l_1p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_l_1p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_l_1p5.root pt7 DoubleBM2 Double results doubleBLpt1
echo "SF[0]"
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_l_1p5.root pt7 DoubleBH Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_l_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_l_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_l_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_l_1p5.root pt5 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_1p5.root pt5 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_1p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_1p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_1p5.root pt4 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_1p5.root pt4 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_l_1p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_l_1p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_l_1p5.root pt6 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_l_1p5.root pt6 DoubleBH Double results doubleBLpt1
echo "SF[0]"

echo "cfromg 1p5"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_cfromg_1p5.root pt7 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_cfromg_1p5.root pt7 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_cfromg_1p5.root pt7 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_cfromg_1p5.root pt7 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBL_cfromg_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM1_cfromg_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBM2_cfromg_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuDiJet170Mu5_run2016G-H_pt250_DoubleBH_cfromg_1p5.root pt5 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_1p5.root pt5 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_1p5.root pt5 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_1p5.root pt5 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_1p5.root pt5 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_1p5.root pt4 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_1p5.root pt4 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_1p5.root pt4 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_1p5.root pt4 DoubleBH Double results doubleBLpt1
echo "SF[0]"
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBL_cfromg_1p5.root pt6 DoubleBL Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM1_cfromg_1p5.root pt6 DoubleBM1 Double results doubleBLpt1
./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBM2_cfromg_1p5.root pt6 DoubleBM2 Double results doubleBLpt1
#./test normGH/Final_histograms_btagval_optimized_doublemu_BTagMu_QCDMuEnriched_HLTBTagMuAK8Jet300Mu5_run2016G-H_pt350_DoubleBH_cfromg_1p5.root pt6 DoubleBH Double results doubleBLpt1
echo "SF[0]"